version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - 8000
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: